### ISSUE TITLE
automap function on SelectBuilder object does not work

### ISSUE THREAD

**Issue by adam-mahmood** [davidmoten/rxjava2-jdbc#1] opened 2017-09-19 15:31 UTC
db.select( "SELECT RecIndex,Site FROM dbo.MEAS_CARRIER where Time >= ? ORDER BY RecIndex ASC")              .parameterStream(Flowable.just(Instant.now().minus(Duration.ofHours(1).plus(Duration.ofMinutes(2))))
                        .delay(1, TimeUnit.SECONDS).repeat())
                .autoMap(CarrierMeasuremnt.class).distinct();

Your automap function returns a Flowable, and when you subscribe to the Flowable the value is null!

Can you please help?

**Comment by davidmoten** [comment] 2017-09-19 16:02
Thanks for the report, I'll have a look.

**Comment by davidmoten** [comment] 2017-09-19 16:35
I think the problem is that the automapped object returns `null` from the `toString` method so you think you have a null object but you don't. Here's a runnable example using the `Database.test()` method:

```java
Database.test() //
    .select("select score from person where name=?") //
    .parameterStream(Flowable.just("FRED")) //
    .autoMap(Score.class) //
    .doOnNext(System.out::println) //
    .doOnNext(x -> System.out.println(x.score())) //
    .blockingSubscribe();

interface Score {
    @Column
    int score();
}
```
The output is:
```
null
21
```
The behaviour is definitely confusing so I'll make a change to generate a meaningful message from the automapped object's `toString` method.

**Comment by davidmoten** [comment] 2017-09-19 17:19
I've deployed 0.1-RC2 to Maven Central with the `toString` method enhancement. Let me know if your issue is solved now.

**Comment by adam-mahmood** [comment] 2017-09-19 19:39
Thank you David. I believe that has fixed the issue, however i will test at work tomorrow morning. 
I must say you have done a brilliant job in creating this  library.

**Comment by davidmoten** [comment] 2017-09-20 05:37
Glad you like it @adam-mahmood. By the way use 0.1-RC3 to pick up another fix. Cheers.

**Comment by davidmoten** [comment] 2017-09-22 13:04
Closing this because conversation is continuing in #3

**Closed by davidmoten** 2017-09-22 13:04 UTC
Labels: enhancement
